# Generated by Django 5.2.17 on 2026-09-24 07:43

import django.db.models.deletion
import pronto_web.reports.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlignmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("saved_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SAVE", "SAVE"),
                            ("COPY", "COPY"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_events",
                        to="reports.reportrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedAlignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sample_id", models.CharField(max_length=128)),
                (
                    "reference_build",
                    models.CharField(
                        choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TUMOUR_DNA", "TUMOUR_DNA"),
                            ("NORMAL_DNA", "NORMAL_DNA"),
                            ("TUMOUR_RNA", "TUMOUR_RNA"),
                            ("NORMAL_RNA", "NORMAL_RNA"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("bam", "bam"), ("cram", "cram")], max_length=4
                    ),
                ),
                ("data_key", models.CharField(max_length=64, unique=True)),
                ("index_key", models.CharField(max_length=64, unique=True)),
                ("data_size", models.PositiveBigIntegerField()),
                ("index_size", models.PositiveBigIntegerField()),
                ("data_sha256", models.CharField(max_length=64)),
                ("index_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("READY", "READY"), ("DELETING", "DELETING")],
                        default="READY", max_length=8
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saved_alignments",
                        to="reports.reportrecord",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlignmentUploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sample_id", models.CharField(max_length=128)),
                (
                    "reference_build",
                    models.CharField(
                        choices=[("GRCh37", "GRCh37"), ("GRCh38", "GRCh38")],
                        max_length=16,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TUMOUR_DNA", "TUMOUR_DNA"),
                            ("NORMAL_DNA", "NORMAL_DNA"),
                            ("TUMOUR_RNA", "TUMOUR_RNA"),
                            ("NORMAL_RNA", "NORMAL_RNA"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("bam", "bam"), ("cram", "cram")], max_length=4
                    ),
                ),
                ("expected_data_size", models.PositiveBigIntegerField()),
                ("expected_index_size", models.PositiveBigIntegerField()),
                ("received_data_bytes", models.PositiveBigIntegerField(default=0)),
                ("received_index_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "staging_data_key",
                    models.CharField(
                        default=pronto_web.reports.models.opaque_alignment_key,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "staging_index_key",
                    models.CharField(
                        default=pronto_web.reports.models.opaque_alignment_key,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("VALIDATING", "VALIDATING"),
                            ("COMPLETED", "COMPLETED"),
                            ("CANCELLED", "CANCELLED"),
                            ("FAILED", "FAILED"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alignment_uploads",
                        to="reports.reportrecord",
                    ),
                ),
                (
                    "saved_alignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reports.savedalignment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportWriteGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alignment_write_grants",
                        to="reports.reportrecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "user"), name="unique_report_write_grant"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="savedalignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "READY")),
                fields=("report", "sample_id", "reference_build", "role"),
                name="unique_ready_alignment_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedalignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["READY", "DELETING"])),
                name="saved_alignment_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedalignment",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_size__gt", 0), ("index_size__gt", 0)),
                name="saved_alignment_sizes_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="alignmentuploadsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["OPEN", "VALIDATING", "COMPLETED", "CANCELLED", "FAILED"])),
                name="upload_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="alignmentuploadsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_data_size__gt", 0), ("expected_index_size__gt", 0)
                ),
                name="upload_expected_sizes_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="alignmentuploadsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("received_data_bytes__lte", models.F("expected_data_size")),
                    ("received_index_bytes__lte", models.F("expected_index_size")),
                ),
                name="upload_offsets_in_bounds",
            ),
        ),
    ]
