# Generated by Django 5.2.17 on 2026-09-26 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_initials_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportPrintAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("request_id", models.UUIDField()),
                ("declared_initials", models.CharField(max_length=8)),
                (
                    "attribution_method",
                    models.CharField(default="SELF_REPORTED", max_length=16),
                ),
                ("action", models.CharField(default="PRINT_REQUESTED", max_length=16)),
                ("requested_at", models.DateTimeField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reports.reportrecord",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report", "request_id"),
                        name="unique_report_print_request",
                    )
                ],
            },
        ),
    ]
