# Generated by Django 5.2.17 on 2026-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0008_presentation_figures_pdf_exports"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportpdfexportaudit",
            name="actor_label",
            field=models.CharField(blank=True, max_length=301, null=True),
        ),
        migrations.AddField(
            model_name="reportpdfexportaudit",
            name="attribution_method",
            field=models.CharField(default="SELF_REPORTED", max_length=16),
        ),
        migrations.AlterField(
            model_name="reportpdfexportaudit",
            name="declared_initials",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
